compile:
	npx hardhat compile

deploy:
	npx hardhat ignition deploy ./ignition/modules/HealthToken.ts --network ganache

deploy_medical:
	npx hardhat ignition deploy ./ignition/modules/Medical.ts --network ganache

